-- ============================================================
-- Proyecto: SS2-CONOSE-OCCIDENTE
-- Modulo: Arte y Artesanía / Expresiones Culturales
-- Migracion: V20260706180000__ddl_artesania.sql
-- Motor: PostgreSQL
-- Convenciones aplicadas:
--   - No se usa search_path.
--   - Todos los objetos se califican con el esquema artesania.
--   - Tablas de dominio incluyen carga_id INT REFERENCES meta.carga(id).
--   - Tablas y columnas se documentan con COMMENT ON.
-- ============================================================

CREATE SCHEMA IF NOT EXISTS artesania;

COMMENT ON SCHEMA artesania IS 'Esquema para el módulo de Arte y Artesanía, que cubre textiles, cerámica, madera, jade, marimbas, pintura y otras expresiones culturales del Altiplano Occidental.';

-- 1. tipo_obra_arte
CREATE TABLE IF NOT EXISTS artesania.tipo_obra_arte (
    id_tipo_obra INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       VARCHAR(80)  NOT NULL UNIQUE,
    nombre       VARCHAR(120) NOT NULL UNIQUE,
    descripcion  TEXT,
    categoria_general VARCHAR(80) NOT NULL,
    carga_id     INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE artesania.tipo_obra_arte IS 'Catálogo de tipos de expresiones artísticas o artesanales.';
COMMENT ON COLUMN artesania.tipo_obra_arte.id_tipo_obra IS 'Identificador único del tipo de obra.';
COMMENT ON COLUMN artesania.tipo_obra_arte.codigo IS 'Código estable del tipo de obra para integraciones y ETL.';
COMMENT ON COLUMN artesania.tipo_obra_arte.nombre IS 'Nombre del tipo de obra (ej. TEXTIL, CERAMICA, PINTURA).';
COMMENT ON COLUMN artesania.tipo_obra_arte.descripcion IS 'Descripción del tipo de expresión artística.';
COMMENT ON COLUMN artesania.tipo_obra_arte.categoria_general IS 'Categoría general (ej. ARTESANIA, ARTES_VISUALES, ARTES_ESCENICAS).';
COMMENT ON COLUMN artesania.tipo_obra_arte.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 2. tecnica_artesanal
CREATE TABLE IF NOT EXISTS artesania.tecnica_artesanal (
    id_tecnica   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       VARCHAR(80)  NOT NULL UNIQUE,
    nombre       VARCHAR(120) NOT NULL UNIQUE,
    origen_historico TEXT,
    descripcion  TEXT,
    carga_id     INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE artesania.tecnica_artesanal IS 'Técnicas tradicionales y contemporáneas aplicadas en la creación de obras.';
COMMENT ON COLUMN artesania.tecnica_artesanal.id_tecnica IS 'Identificador único de la técnica.';
COMMENT ON COLUMN artesania.tecnica_artesanal.codigo IS 'Código estable de la técnica.';
COMMENT ON COLUMN artesania.tecnica_artesanal.nombre IS 'Nombre de la técnica (ej. Jaspe, Telar de cintura, Modelado de barro).';
COMMENT ON COLUMN artesania.tecnica_artesanal.origen_historico IS 'Información sobre el origen histórico de la técnica.';
COMMENT ON COLUMN artesania.tecnica_artesanal.descripcion IS 'Descripción técnica de la metodología de trabajo.';
COMMENT ON COLUMN artesania.tecnica_artesanal.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 3. material_arte
CREATE TABLE IF NOT EXISTS artesania.material_arte (
    id_material  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       VARCHAR(80)  NOT NULL UNIQUE,
    nombre       VARCHAR(120) NOT NULL UNIQUE,
    descripcion  TEXT,
    carga_id     INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE artesania.material_arte IS 'Catálogo de materias primas o materiales utilizados en las obras.';
COMMENT ON COLUMN artesania.material_arte.id_material IS 'Identificador único del material.';
COMMENT ON COLUMN artesania.material_arte.codigo IS 'Código estable del material.';
COMMENT ON COLUMN artesania.material_arte.nombre IS 'Nombre del material (ej. Hilo de algodón, Madera de hormigo, Jade).';
COMMENT ON COLUMN artesania.material_arte.descripcion IS 'Descripción del material y sus propiedades.';
COMMENT ON COLUMN artesania.material_arte.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 4. taller_colectivo
CREATE TABLE IF NOT EXISTS artesania.taller_colectivo (
    id_taller       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(80)  NOT NULL UNIQUE,
    nombre          VARCHAR(220) NOT NULL UNIQUE,
    representante   VARCHAR(180),
    departamento_id INT NOT NULL REFERENCES geografia.departamento(id),
    municipio_id    INT REFERENCES geografia.municipio(id),
    direccion       VARCHAR(350),
    anio_fundacion  INT,
    cantidad_miembros INT NOT NULL DEFAULT 1,
    contacto        VARCHAR(150),
    carga_id        INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE artesania.taller_colectivo IS 'Talleres colectivos, cooperativas y asociaciones familiares de artesanos.';
COMMENT ON COLUMN artesania.taller_colectivo.id_taller IS 'Identificador único del taller o colectivo.';
COMMENT ON COLUMN artesania.taller_colectivo.codigo IS 'Código estable del taller.';
COMMENT ON COLUMN artesania.taller_colectivo.nombre IS 'Nombre oficial del taller o colectivo.';
COMMENT ON COLUMN artesania.taller_colectivo.representante IS 'Nombre del maestro artesano o líder representante.';
COMMENT ON COLUMN artesania.taller_colectivo.departamento_id IS 'Departamento oficial de ubicación del taller.';
COMMENT ON COLUMN artesania.taller_colectivo.municipio_id IS 'Municipio oficial de ubicación del taller.';
COMMENT ON COLUMN artesania.taller_colectivo.direccion IS 'Dirección o paraje detallado del taller.';
COMMENT ON COLUMN artesania.taller_colectivo.anio_fundacion IS 'Año aproximado de fundación.';
COMMENT ON COLUMN artesania.taller_colectivo.cantidad_miembros IS 'Cantidad de artesanos activos en el colectivo.';
COMMENT ON COLUMN artesania.taller_colectivo.contacto IS 'Datos de contacto del taller.';
COMMENT ON COLUMN artesania.taller_colectivo.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 5. artista_artesano
CREATE TABLE IF NOT EXISTS artesania.artista_artesano (
    id_artista            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                VARCHAR(80)  NOT NULL UNIQUE,
    nombre_completo       VARCHAR(220) NOT NULL,
    genero                VARCHAR(20),
    fecha_nacimiento      DATE,
    departamento_id       INT NOT NULL REFERENCES geografia.departamento(id),
    municipio_id          INT REFERENCES geografia.municipio(id),
    taller_id             INT REFERENCES artesania.taller_colectivo(id_taller),
    especialidad_principal VARCHAR(150) NOT NULL,
    reconocimientos       TEXT,
    carga_id              INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE artesania.artista_artesano IS 'Maestros artesanos y artistas de las diversas ramas en la región.';
COMMENT ON COLUMN artesania.artista_artesano.id_artista IS 'Identificador único del artista/artesano.';
COMMENT ON COLUMN artesania.artista_artesano.codigo IS 'Código estable de identificación del artista.';
COMMENT ON COLUMN artesania.artista_artesano.nombre_completo IS 'Nombre completo del artista/artesano.';
COMMENT ON COLUMN artesania.artista_artesano.genero IS 'Género del artista/artesano.';
COMMENT ON COLUMN artesania.artista_artesano.fecha_nacimiento IS 'Fecha de nacimiento.';
COMMENT ON COLUMN artesania.artista_artesano.departamento_id IS 'Departamento oficial de origen/residencia.';
COMMENT ON COLUMN artesania.artista_artesano.municipio_id IS 'Municipio oficial de origen/residencia.';
COMMENT ON COLUMN artesania.artista_artesano.taller_id IS 'Taller o colectivo al que pertenece, si aplica.';
COMMENT ON COLUMN artesania.artista_artesano.especialidad_principal IS 'Especialidad principal del artista (ej. Pintura Primitivista, Marimbista).';
COMMENT ON COLUMN artesania.artista_artesano.reconocimientos IS 'Listado de premios, distinciones o trayectoria.';
COMMENT ON COLUMN artesania.artista_artesano.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 6. obra_arte_artesania
CREATE TABLE IF NOT EXISTS artesania.obra_arte_artesania (
    id_obra                       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                        VARCHAR(80)  NOT NULL UNIQUE,
    nombre                        VARCHAR(220) NOT NULL,
    tipo_obra_id                  INT NOT NULL REFERENCES artesania.tipo_obra_arte(id_tipo_obra),
    artista_id                    INT REFERENCES artesania.artista_artesano(id_artista),
    taller_id                     INT REFERENCES artesania.taller_colectivo(id_taller),
    descripcion                   TEXT NOT NULL,
    tiempo_estimado_creacion_dias INT,
    precio_sugerido_q             NUMERIC(10, 2),
    carga_id                      INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE artesania.obra_arte_artesania IS 'Ficha técnica de obras, piezas o expresiones artísticas específicas.';
COMMENT ON COLUMN artesania.obra_arte_artesania.id_obra IS 'Identificador único de la obra.';
COMMENT ON COLUMN artesania.obra_arte_artesania.codigo IS 'Código estable de la obra.';
COMMENT ON COLUMN artesania.obra_arte_artesania.nombre IS 'Nombre o título descriptivo de la obra.';
COMMENT ON COLUMN artesania.obra_arte_artesania.tipo_obra_id IS 'Tipo de obra asociada.';
COMMENT ON COLUMN artesania.obra_arte_artesania.artista_id IS 'Referencia al artista/artesano creador.';
COMMENT ON COLUMN artesania.obra_arte_artesania.taller_id IS 'Referencia al taller o colectivo creador (si aplica).';
COMMENT ON COLUMN artesania.obra_arte_artesania.descripcion IS 'Descripción artística o artesanal de la pieza.';
COMMENT ON COLUMN artesania.obra_arte_artesania.tiempo_estimado_creacion_dias IS 'Tiempo estimado de elaboración en días.';
COMMENT ON COLUMN artesania.obra_arte_artesania.precio_sugerido_q IS 'Precio sugerido de venta en Quetzales.';
COMMENT ON COLUMN artesania.obra_arte_artesania.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 7. obra_tecnica
CREATE TABLE IF NOT EXISTS artesania.obra_tecnica (
    obra_id    INT NOT NULL REFERENCES artesania.obra_arte_artesania(id_obra) ON DELETE CASCADE,
    tecnica_id INT NOT NULL REFERENCES artesania.tecnica_artesanal(id_tecnica),
    carga_id   INT REFERENCES meta.carga(id),
    PRIMARY KEY (obra_id, tecnica_id)
);

COMMENT ON TABLE artesania.obra_tecnica IS 'Relación muchos a muchos entre obras y técnicas aplicadas.';
COMMENT ON COLUMN artesania.obra_tecnica.obra_id IS 'Identificador de la obra.';
COMMENT ON COLUMN artesania.obra_tecnica.tecnica_id IS 'Identificador de la técnica aplicada.';
COMMENT ON COLUMN artesania.obra_tecnica.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 8. obra_material
CREATE TABLE IF NOT EXISTS artesania.obra_material (
    obra_id             INT NOT NULL REFERENCES artesania.obra_arte_artesania(id_obra) ON DELETE CASCADE,
    material_id         INT NOT NULL REFERENCES artesania.material_arte(id_material),
    proporcion_estimada NUMERIC(5, 2),
    carga_id            INT REFERENCES meta.carga(id),
    PRIMARY KEY (obra_id, material_id)
);

COMMENT ON TABLE artesania.obra_material IS 'Relación muchos a muchos entre obras y materiales con proporciones.';
COMMENT ON COLUMN artesania.obra_material.obra_id IS 'Identificador de la obra.';
COMMENT ON COLUMN artesania.obra_material.material_id IS 'Identificador del material utilizado.';
COMMENT ON COLUMN artesania.obra_material.proporcion_estimada IS 'Proporción porcentual estimada del material en la pieza.';
COMMENT ON COLUMN artesania.obra_material.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 9. produccion_artesanal_municipal
CREATE TABLE IF NOT EXISTS artesania.produccion_artesanal_municipal (
    id_produccion              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departamento_id            INT NOT NULL REFERENCES geografia.departamento(id),
    municipio_id               INT REFERENCES geografia.municipio(id),
    tipo_obra_id               INT NOT NULL REFERENCES artesania.tipo_obra_arte(id_tipo_obra),
    anio                       INT NOT NULL,
    volumen_estimado_unidades  INT NOT NULL,
    valor_estimado_mercado_q   NUMERIC(12, 2) NOT NULL,
    cantidad_artesanos_activos INT NOT NULL,
    carga_id                   INT REFERENCES meta.carga(id),
    CONSTRAINT uq_artesania_produccion_mun UNIQUE (municipio_id, tipo_obra_id, anio)
);

COMMENT ON TABLE artesania.produccion_artesanal_municipal IS 'Estimaciones anuales del volumen, valor comercial y artesanos activos por municipio.';
COMMENT ON COLUMN artesania.produccion_artesanal_municipal.id_produccion IS 'Identificador único del registro de producción.';
COMMENT ON COLUMN artesania.produccion_artesanal_municipal.departamento_id IS 'Departamento oficial verificado.';
COMMENT ON COLUMN artesania.produccion_artesanal_municipal.municipio_id IS 'Municipio oficial verificado.';
COMMENT ON COLUMN artesania.produccion_artesanal_municipal.tipo_obra_id IS 'Tipo de obra evaluado.';
COMMENT ON COLUMN artesania.produccion_artesanal_municipal.anio IS 'Año del registro estadístico.';
COMMENT ON COLUMN artesania.produccion_artesanal_municipal.volumen_estimado_unidades IS 'Volumen estimado de piezas anuales producidas.';
COMMENT ON COLUMN artesania.produccion_artesanal_municipal.valor_estimado_mercado_q IS 'Valor total estimado de mercado en Quetzales.';
COMMENT ON COLUMN artesania.produccion_artesanal_municipal.cantidad_artesanos_activos IS 'Cantidad estimada de artesanos activos en este rubro.';
COMMENT ON COLUMN artesania.produccion_artesanal_municipal.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 10. evento_exposicion_arte
CREATE TABLE IF NOT EXISTS artesania.evento_exposicion_arte (
    id_evento       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(80)  NOT NULL UNIQUE,
    nombre          VARCHAR(220) NOT NULL UNIQUE,
    fecha_inicio    DATE NOT NULL,
    fecha_fin       DATE NOT NULL,
    departamento_id INT NOT NULL REFERENCES geografia.departamento(id),
    municipio_id    INT REFERENCES geografia.municipio(id),
    lugar_detallado VARCHAR(350),
    organizador     VARCHAR(180),
    carga_id        INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE artesania.evento_exposicion_arte IS 'Eventos, ferias, exposiciones y festivales culturales de arte y artesanía.';
COMMENT ON COLUMN artesania.evento_exposicion_arte.id_evento IS 'Identificador único del evento.';
COMMENT ON COLUMN artesania.evento_exposicion_arte.codigo IS 'Código estable de identificación del evento.';
COMMENT ON COLUMN artesania.evento_exposicion_arte.nombre IS 'Nombre oficial del evento o exposición.';
COMMENT ON COLUMN artesania.evento_exposicion_arte.fecha_inicio IS 'Fecha de inicio del evento.';
COMMENT ON COLUMN artesania.evento_exposicion_arte.fecha_fin IS 'Fecha de finalización del evento.';
COMMENT ON COLUMN artesania.evento_exposicion_arte.departamento_id IS 'Departamento oficial de sede del evento.';
COMMENT ON COLUMN artesania.evento_exposicion_arte.municipio_id IS 'Municipio oficial de sede del evento.';
COMMENT ON COLUMN artesania.evento_exposicion_arte.lugar_detallado IS 'Descripción del lugar físico o centro del evento.';
COMMENT ON COLUMN artesania.evento_exposicion_arte.organizador IS 'Institución, cooperativa u organizador principal.';
COMMENT ON COLUMN artesania.evento_exposicion_arte.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 11. participante_evento
CREATE TABLE IF NOT EXISTS artesania.participante_evento (
    evento_id             INT NOT NULL REFERENCES artesania.evento_exposicion_arte(id_evento) ON DELETE CASCADE,
    artista_id            INT REFERENCES artesania.artista_artesano(id_artista),
    taller_id             INT REFERENCES artesania.taller_colectivo(id_taller),
    premio_reconocimiento VARCHAR(250),
    carga_id              INT REFERENCES meta.carga(id),
    CONSTRAINT ck_artesania_participante CHECK (artista_id IS NOT NULL OR taller_id IS NOT NULL)
);

COMMENT ON TABLE artesania.participante_evento IS 'Registro de artistas y talleres colectivos participantes en eventos y sus reconocimientos.';
COMMENT ON COLUMN artesania.participante_evento.evento_id IS 'Identificador del evento.';
COMMENT ON COLUMN artesania.participante_evento.artista_id IS 'Artista individual participante (opcional).';
COMMENT ON COLUMN artesania.participante_evento.taller_id IS 'Taller colectivo participante (opcional).';
COMMENT ON COLUMN artesania.participante_evento.premio_reconocimiento IS 'Premio, mención o reconocimiento obtenido.';
COMMENT ON COLUMN artesania.participante_evento.carga_id IS 'Referencia al registro de carga de metadatos.';

-- Índices adicionales para optimización de consultas recurrentes
CREATE INDEX IF NOT EXISTS ix_artista_municipio ON artesania.artista_artesano(municipio_id);
CREATE INDEX IF NOT EXISTS ix_taller_municipio ON artesania.taller_colectivo(municipio_id);
CREATE INDEX IF NOT EXISTS ix_obra_tipo ON artesania.obra_arte_artesania(tipo_obra_id);
CREATE INDEX IF NOT EXISTS ix_produccion_mun ON artesania.produccion_artesanal_municipal(municipio_id);
CREATE INDEX IF NOT EXISTS ix_evento_municipio ON artesania.evento_exposicion_arte(municipio_id);
