-- =============================================================================
-- Módulo Justicia — Seed nómina CR (100 registros)
-- Ejecutar después de V20260705000001__seed_renglon_presupuestario.sql
-- Fuente: Congreso de la República — LAIP Art. 10 Inciso 4
-- Archivos: CR/2023/Renglon_011.csv (34), Renglon_022.csv (33), Renglon_029.csv (33)
-- Año reportado en archivo 011/022: Enero 2025 | archivo 029: Febrero 2025
-- Nota: Salarios en formato "Q16,106.98" → 16106.98 (Q=símbolo, coma=miles)
-- =============================================================================

INSERT INTO justicia.nomina_publica
    (sigla_institucion, anio, mes, nombre, puesto, unidad, renglon_id, salario, fuente, archivo_origen)
VALUES
-- =========================================================================
-- RENGLÓN 011 — Personal permanente (34 registros)
-- Fuente: Renglon_011.csv — Lista general Enero 2025
-- =========================================================================
('CR', 2025, 1, 'RIVAS MORATAYA MARIA ALEJANDRA',                        'ASISTENTE I',    'BLOQUE LEGISLATIVO CREO',                                            (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 16106.98, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'PADILLA ALVAREZ WALTTER ANIBAL',                        'ASISTENTE I',    'BLOQUE LEGISLATIVO CREO',                                            (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 13000.00, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'BARAHONA DIAZ ISRAEL',                                  'TECNICO I',      'BLOQUE LEGISLATIVO PARTIDO POLITICO VISION CON VALORES -VIVA-',      (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 22442.92, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'OLIVA ALVIZURES GLORIA ELIZABETH',                      'ASISTENTE I',    'BLOQUE LEGISLATIVO UNE',                                             (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 16037.70, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'MORAN SOSA MAYNOR RAFAEL',                              'ASISTENTE I',    'BLOQUE LEGISLATIVO UNE',                                             (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 25203.83, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'CUELLAR ARDON CLAUDIA PATRICIA',                        'ASISTENTE I',    'BLOQUE LEGISLATIVO UNE',                                             (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 18214.90, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'QUIXTAN DUBON AIDA DEL ROSARIO',                        'ASISTENTE I',    'BLOQUE LEGISLATIVO -UNE-',                                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 20710.10, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'DEL CID MEDRANO MAX ESTUARDO',                          'ASISTENTE I',    'BLOQUE LEGISLATIVO VAMOS',                                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 17222.63, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'PEREZ GOMEZ MIZAEL',                                    'TECNICO I',      'BLOQUE LEGISLATIVO VAMOS',                                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9457.50, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'VILLEDA ROBLES MARIA ALEJANDRA',                        'ASISTENTE I',    'BLOQUE LEGISLATIVO VOS',                                             (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 21318.89, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'LEWIN WENDY EUGENIA',                                   'ASISTENTE I',    'COMISION DE COMUNICACIONES TRANSPORTE Y OBRAS PUBLICAS',             (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 21766.50, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'HERNANDEZ LOPEZ MARIA ALEJANDRA',                       'ASISTENTE III',  'COMISION DE EDUCACION CIENCIA Y TECNOLOGIA',                         (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 20000.00, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'BARCO GARCIA OSCAR ANIBAL',                             'OPERATIVO I',    'COMISION DE GOBERNACION',                                            (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  5675.00, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'DIAZ VALLADARES DE SAN PEDRO MARIA GABRIELA',           'ASISTENTE I',    'COMISION DE PREVISION Y SEGURIDAD SOCIAL',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 15150.00, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'RIVERA CASTILLO CYNTHIA LISBETH',                       'TECNICO I',      'DIPUTADA ALMA LUZ GUERRERO DE LA CRUZ',                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 22717.83, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'DELGADO GIL CARMEN JANNETT',                            'ASISTENTE I',    'DIPUTADA ALMA LUZ GUERRERO DE LA CRUZ',                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 18803.13, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'DUARTE BARILLAS CESAR AMAUDY',                          'TECNICO III',    'DIPUTADA ANA LUCRECIA MARROQUIN GODOY DE PALOMO',                    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 28103.70, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'RIVERA RECINOS JENNIFER KIMBERLY ROSSANA',              'ASISTENTE III',  'DIPUTADA ANA LUCRECIA MARROQUIN GODOY DE PALOMO',                    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 24276.10, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'LOPEZ Y LOPEZ ELISABETH',                               'ASISTENTE I',    'DIPUTADA ANDREA BEATRIZ VILLAGRAN ANTON DE PANTOJA',                 (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 29150.00, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'PEREZ CASTELLANOS LUIS MARCELO',                        'TECNICO I',      'DIPUTADA ANDREA BEATRIZ VILLAGRAN ANTON DE PANTOJA',                 (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 13087.50, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'LOPEZ ORTIZ PABLO ROBERTO',                             'TECNICO I',      'DIPUTADA ANDREA BEATRIZ VILLAGRAN ANTON DE PANTOJA',                 (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9250.00, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'VALENZUELA DE PAZ LESLY',                               'ASISTENTE I',    'DIPUTADA ANDREA MARIA REYES ZECENA',                                 (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 24186.33, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'TIRADO OCHOA HENRY BENEDICTO',                          'OPERATIVO I',    'DIPUTADA DAMARIS CAROLINA CERNA ACEVEDO DE MAURICIO',                (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9523.35, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'MONTENEGRO VASQUEZ ADRIAN ADOLFO',                      'ASISTENTE I',    'DIPUTADA EVELYN ODDETH MORATAYA MARROQUIN',                          (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 18507.50, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'FALLAS ALEJANDRO ABELINO',                              'TECNICO I',      'DIPUTADA GLADIS CAROLINA CIFUENTES BARRAGAN',                        (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 14431.35, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'RIVAS VASQUEZ CLAUDIA MARIA MARICEL',                   'ASISTENTE III',  'DIPUTADA GLADIS CAROLINA CIFUENTES BARRAGAN',                        (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 18097.50, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'QUINONEZ GARCIA SERGIO ESTUARDO',                       'OPERATIVO III',  'DIPUTADA GREICY DOMENICA DE LEON DE LEON',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9100.00, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'GALVEZ JEREZANO DE CONTRERAS ANA PATRICIA',             'ASISTENTE I',    'DIPUTADA GREICY DOMENICA DE LEON DE LEON',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 18507.50, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'HERNANDEZ SALGUERO DE PATAN LISBETH DEL CARMEN',        'TECNICO I',      'DIPUTADA GREICY DOMENICA DE LEON DE LEON',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 10013.28, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'RODRIGUEZ ESPINOZA OSCAR ALEJANDRO',                    'TECNICO I',      'DIPUTADA GREICY DOMENICA DE LEON DE LEON',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9450.00, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'LUCERO SUAREZ YOBANY FERNANDO',                         'ASISTENTE I',    'DIPUTADA IVANNA MARIA LUJAN PADILLA',                                (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 29150.00, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'CASTELLANOS MORALES LESBIA AURORA',                     'TECNICO I',      'DIPUTADA IVANNA MARIA LUJAN PADILLA',                                (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 10150.00, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'GARCIA LOPEZ CLAUDIA ELIZABETH',                        'TECNICO III',    'DIPUTADA KARINA ALEXANDRA PAZ ROSALES',                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 24481.32, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),
('CR', 2025, 1, 'PINTO DE LEON JULIO ALFONSO',                           'ASISTENTE I',    'DIPUTADA KARINA ALEXANDRA PAZ ROSALES',                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 16673.53, 'CR — LAIP Enero 2025', 'Renglon_011.csv'),

-- =========================================================================
-- RENGLÓN 022 — Personal por contrato (33 registros)
-- Fuente: Renglon_022.csv — Lista general Enero 2025
-- =========================================================================
('CR', 2025, 1, 'JIMENEZ DIAZ JORGE ARTURO',                             'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO AZUL',    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'MENENDEZ CALDERON MARIO ALBERTO',                       'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO AZUL',    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'DE LEON CASTELLANOS FRIDEL OMAR',                       'ASESOR PARLAMENTARIO I - 38 B',   'BLOQUE LEGISLATIVO BIEN',    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 18000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'PACHECO PINEDA ANA SOFIA',                              'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO BIEN',    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'JAVIER LOPEZ JOSE LUIS',                                'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO -BIEN-',  (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'MONTERROSO DE LEON LUIS ENRIQUE',                       'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO CABAL',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'LUCAS LOPEZ MANUEL BENEDICTO',                          'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO CABAL',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'CATAVI PAREDES EDWIN ALEXANDER',                        'ASESOR PARLAMENTARIO I - 38 B',   'BLOQUE LEGISLATIVO CABAL',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 18000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'CERIN ALDANA EDVIN',                                    'ASESOR PARLAMENTARIO I - 38 B',   'BLOQUE LEGISLATIVO CABAL',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 18000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'FLORES ALVARADO ELBA LORENA',                           'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO CABAL',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'BOLANOS MANCIO ELDYN RENE',                             'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO CABAL',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'CONDE SAMAYOA JOSE ALEJANDRO',                          'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO CABAL',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'LEMUS BARRIENTOS HERBERTH ESTTIDH',                     'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO CABAL',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'ACEVEDO RAMIREZ MARIO ISAAC',                           'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO CAMBIO',  (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'MURALLES RIVERA MARLON JOSE',                           'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO CREO',    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'SOLARES CALDERON MARJORIE KATE SOFIA',                  'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO CREO',    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'BAUER FIGUEROA ESTEFANIA',                              'ASESOR PARLAMENTARIO II - 38 B',  'BLOQUE LEGISLATIVO CREO',    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 20000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'RAMIREZ CURLEY WERNER ROBERTO',                         'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO ELEFANTE',(SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'CABRERA CEDILLO DE HERNANDEZ ZORAIDA MARIELA',          'ASESOR PARLAMENTARIO II - 38 B',  'BLOQUE LEGISLATIVO ELEFANTE',(SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 20000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'SANTIZO GOMEZ VICTOR FERNANDO',                         'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO NOSOTROS',(SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'MIRANDA MALDONADO LUIS FELIPE',                         'ASESOR PARLAMENTARIO I - 38 B',   'BLOQUE LEGISLATIVO NOSOTROS',(SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 18000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'CASASOLA FONSECA CLAUDIA SUSETH',                       'ASESOR PARLAMENTARIO I - 38 B',   'BLOQUE LEGISLATIVO TODOS',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 18000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'LOPEZ ALVARADO DE HERRERA KARLA YANETH',                'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO TODOS',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'REYNA MONTENEGRO PEDRO ANTONIO',                        'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO TODOS',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'PEREZ ANLEU CARLOS GABRIEL',                            'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO -UNE-',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'IMERI GUZMAN JULIO CESAR',                              'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO -UNE-',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'ROMANO VILLATORO CESAR RODOLFO',                        'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO -UNE-',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'COTO DIAZ DE CASTELLANOS ASTRID ARELY',                 'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO -UNE-',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'GONZALEZ VILLEDA MOISES AARON',                         'ASESOR PARLAMENTARIO I - 38 B',   'BLOQUE LEGISLATIVO -UNE-',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 18000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'AGUILAR LOPEZ CRISTIAN ALEXANDER',                      'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO -UNE-',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'SOLIS JUAREZ WERNER ALEXANDERD',                        'ASESOR PARLAMENTARIO III - 38 B', 'BLOQUE LEGISLATIVO -UNE-',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 22000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'CANO ALVARADO JOSE FERNANDO',                           'ASESOR PARLAMENTARIO II - 38 B',  'BLOQUE LEGISLATIVO -UNE-',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 20000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),
('CR', 2025, 1, 'MUNOZ DE RODAS BEBERLY CRISTELL',                       'ASESOR PARLAMENTARIO II - 38 B',  'BLOQUE LEGISLATIVO -UNE-',   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '022'), 20000.00, 'CR — LAIP Enero 2025', 'Renglon_022.csv'),

-- =========================================================================
-- RENGLÓN 029 — Otras remuneraciones de personal temporal / honorarios (33 registros)
-- Fuente: Renglon_029.csv — Lista general Febrero 2025
-- =========================================================================
('CR', 2025, 2, 'MONGE CABRERA ANA PATRICIA',                            'ASESORA PARLAMENTARIA', 'BLOQUE LEGISLATIVO COMUNIDAD ELEFANTE -ELEFANTE- -SUBJEFATURA-',          (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'MUTZ JUCUB VIVIANA MAGALY',                             'ASESORA PARLAMENTARIA', 'BLOQUE LEGISLATIVO WINAQ-URNG-MAIZ -JEFATURA-',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'BARRIENTOS DE ROCA ALBA MAY LING',                      'ASESOR',                'DIRECCION ADMINISTRATIVA',                                                (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'OROZCO RAMIREZ NOE FRANCISCO',                          'ASISTENTE',             'DIRECCION ADMINISTRATIVA',                                                (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'GIL PALENCIA JORGE EDUARDO',                            'ASESOR',                'DIRECCION DE ASUNTOS JURIDICOS',                                          (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'LOPEZ TOBAR AURORA ESTELA',                             'ASESOR',                'DIRECCION DE ASUNTOS JURIDICOS',                                          (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'GUAMUCH PIRIR OSCAR ENRIQUE',                           'ASESOR',                'DIRECCION DE ASUNTOS JURIDICOS',                                          (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'MEZA AYUSO DE PRADO EMILY STTEPHANY',                   'ASESOR',                'DIRECCION DE ASUNTOS JURIDICOS',                                          (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'TUN ISEM FREDY RONALDO',                                'ASISTENTE',             'DIRECCION DE COMUNICACION SOCIAL Y RELACIONES PUBLICAS',                  (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'MONZON GODOY AMANDA LUCRECIA',                          'ASISTENTE',             'DIRECCION DE COMUNICACION SOCIAL Y RELACIONES PUBLICAS',                  (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'ZEISSIG VASQUEZ OTTO ADOLFO',                           'ASESOR',                'DIRECCION DE ESTUDIOS E INVESTIGACION LEGISLATIVA',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 20000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'VILLAGRAN CAMPOS EMILIO ARNOLDO',                       'ASESOR',                'DIRECCION DE ESTUDIOS E INVESTIGACION LEGISLATIVA',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'FERNANDEZ ROJO JOSE FERNANDO',                          'ASISTENTE',             'DIRECCION DE ESTUDIOS E INVESTIGACION LEGISLATIVA',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'CHIQUIVAL QUIEJU NICOLAS',                              'ASESOR',                'DIRECCION DE ESTUDIOS E INVESTIGACION LEGISLATIVA',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'PEREZ ALVARADO KEVIN EDUARDO',                          'ASISTENTE',             'DIRECCION DE ESTUDIOS E INVESTIGACION LEGISLATIVA',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'SANTOS SALAZAR FABIOLA ELIZABETH DEL CARMEN',           'ASESOR',                'DIRECCION DE ESTUDIOS E INVESTIGACION LEGISLATIVA',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'ROJAS GARCIA DE GOMEZ CARMEN RAQUEL',                   'ASISTENTE',             'DIRECCION DE ESTUDIOS E INVESTIGACION LEGISLATIVA',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'CARDONA HERNANDEZ KEITH DESIREE',                       'ASISTENTE',             'DIRECCION DE ESTUDIOS E INVESTIGACION LEGISLATIVA',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'FIGUEROA CORDOVA OSCAR TULIO',                          'ASISTENTE',             'DIRECCION DE ESTUDIOS E INVESTIGACION LEGISLATIVA',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'MENDEZ HERRERA MARIA JOSE',                             'ASESOR',                'DIRECCION DE ESTUDIOS E INVESTIGACION LEGISLATIVA',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'LOPEZ POP CRISTOFER AARON',                             'ASESOR',                'DIRECCION DE ESTUDIOS E INVESTIGACION LEGISLATIVA',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'VALENCIA LUTIN DE MARROQUI KAREN SUSCELY',              'ASISTENTE',             'DIRECCION DE INFORMATICA Y COMUNICACIONES',                               (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'GUEVARA FRANCO ISRAEL ALEJANDRO',                       'ASESOR',                'DIRECCION DE INFORMATICA Y COMUNICACIONES',                               (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'ORTEGA ARANA LUIS ENRIQUE',                             'ASESOR',                'DIRECCION DE RECURSOS HUMANOS',                                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 20000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'CASTELLANOS RUIZ VICTOR MANUEL DE JESUS',               'ASESOR',                'DIRECCION DE RECURSOS HUMANOS',                                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'OROZCO RAMOS DAYSI VIODELDA',                           'ASISTENTE',             'DIRECCION DE RECURSOS HUMANOS',                                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'CALEL GOMEZ JOSE ABRAHAM',                              'ASISTENTE',             'DIRECCION DE RECURSOS HUMANOS - GESTION DE PERSONAL',                     (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'PAREDES MONTUFAR OSCAR ESTUARDO',                       'ASESOR',                'DIRECCION GENERAL',                                                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'RODRIGUEZ RAMOS FELIPE',                                'ASISTENTE',             'DIRECCION GENERAL',                                                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'PINEDA LOPEZ MILTON SAMUEL',                            'ASISTENTE',             'DIRECCION GENERAL',                                                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'ROSALES ORIZABAL ERICK FERNANDO',                       'ASESOR',                'DIRECCION GENERAL',                                                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 18000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'SANTIAGO GARCIA JUAN RAQUEL',                           'ASISTENTE',             'DIRECCION GENERAL',                                                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'),  8000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv'),
('CR', 2025, 2, 'CASTILLO FARFAN SELVIN TORIBIO',                        'ASISTENTE',             'DIRECCION GENERAL',                                                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '029'), 14000.00, 'CR — LAIP Febrero 2025', 'Renglon_029.csv');
