-- =============================================================================
-- Módulo Justicia — Seed nómina OJ (50 registros)
-- Ejecutar después de V20260705000001__seed_renglon_presupuestario.sql
-- Fuente: Organismo Judicial — Reporte Mensual Enero 2023 (LAIP)
-- Archivo: OJ/2023/Informacion_Trabajadores/01_Enero.csv
-- Nota: Los salarios originales usan formato europeo (punto=miles, coma=decimal).
--       Ejemplo: "50.144,15" se convierte a 50144.15
-- =============================================================================

INSERT INTO justicia.nomina_publica
    (sigla_institucion, anio, mes, nip, nombre, puesto, unidad, renglon_id, salario, fuente, archivo_origen)
VALUES
-- 1–10 Despacho del Fiscal General y Secretaría General
('OJ', 2023, 1, '19960289', 'MARIA CONSUELO PORRAS ARGUETA',           'FISCAL GENERAL DE LA REPUBLICA',                              'DESPACHO DEL FISCAL GENERAL DE LA REPUBLICA',                                     (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 50144.15, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20180695', 'HECTOR ANIBAL DE LEON VELASCO',           'ASESOR DEL DESPACHO DEL FISCAL GENERAL DE LA REPUBLICA',      'DESPACHO DEL FISCAL GENERAL DE LA REPUBLICA',                                     (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 29296.50, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20180653', 'ERIKA YOMARA RODRIGUEZ DEL CID',          'ASISTENTE ADMINISTRATIVO DE DESPACHO II',                     'DESPACHO DEL FISCAL GENERAL DE LA REPUBLICA',                                     (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 17210.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20200175', 'KARLA LORENA MORALES TORRES',             'ASISTENTE DEL ASESOR DEL DESPACHO',                           'DESPACHO DEL FISCAL GENERAL DE LA REPUBLICA',                                     (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9466.34, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20130045', 'GERMAN HUMBERTO GONZALEZ HERNANDEZ',      'AUXILIAR DE OFICINA DEL DESPACHO',                            'DESPACHO DEL FISCAL GENERAL DE LA REPUBLICA',                                     (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  5400.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20050012', 'HERBERTH DOUGLAS MORALES LIMA',           'JEFE DEPARTAMENTO DE COOPERACION',                            'DEPARTAMENTO DE COOPERACION',                                                     (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 17729.46, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20120068', 'MARIAN LISSETTE ABADILLO AGUILAR',        'TECNICO EN COOPERACION I',                                    'DEPARTAMENTO DE COOPERACION',                                                     (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 14055.90, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20150149', 'JESICA ARABALDA ROMERO GARCIA',           'ASISTENTE EJECUTIVO II',                                      'DEPARTAMENTO DE COOPERACION',                                                     (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9466.34, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20030092', 'CARMEN MARIA DONADO VIVAR',               'ASISTENTE EJECUTIVO I',                                       'DEPARTAMENTO DE COOPERACION',                                                     (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  7740.70, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20180554', 'ANGEL ARNOLDO PINEDA AVILA',              'SECRETARIO GENERAL',                                          'SECRETARIA GENERAL',                                                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 34786.50, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),

-- 11–20 Secretaría General
('OJ', 2023, 1, '20211242', 'ERICK EDUARDO SCHAEFFER CABRERA',         'PRIMER SUBSECRETARIO GENERAL',                                'SECRETARIA GENERAL',                                                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 26825.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20220541', 'CARMEN GABRIELA CONTRERAS ALFARO',        'SEGUNDO SUBSECRETARIO GENERAL',                               'SECRETARIA GENERAL',                                                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 25710.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '19950055', 'MARIA LUCIA PATAL CALCA',                 'ASISTENTE ADMINISTRATIVO DE DESPACHO II',                     'SECRETARIA GENERAL',                                                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 17210.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20180535', 'JULIA MARIA JUAREZ SAGUIL',               'ASESOR PROFESIONAL DE SECRETARIA',                            'SECRETARIA GENERAL',                                                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 16807.44, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20130519', 'MAYRA BEATRIZ LOPEZ LOPEZ',               'POLIGRAFISTA',                                                'SECRETARIA GENERAL',                                                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 14710.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20211471', 'MARCO AURELIO RAMIREZ AREVALO',           'ASISTENTE EJECUTIVO IV',                                      'SECRETARIA GENERAL',                                                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 13505.03, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20190353', 'GERMAN ALFREDO JUAREZ BALSECA',           'ASISTENTE EJECUTIVO II',                                      'SECRETARIA GENERAL',                                                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9466.34, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20220350', 'MARIA ELIZABETH LOPEZ MUNOZ',             'ASISTENTE EJECUTIVO II',                                      'SECRETARIA GENERAL',                                                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9466.34, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20190002', 'SINDY GABRIELA GARCIA ROMERO',            'SECRETARIA OFICINISTA III',                                   'SECRETARIA GENERAL',                                                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  7487.70, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20080466', 'LUIS ENRIQUE ESTRADA CANO',               'CONDUCTOR DE VEHICULOS ESPECIAL',                             'SECRETARIA GENERAL',                                                              (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  6299.87, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),

-- 21–27 Secretaría de Asuntos Internacionales y Depto. Cooperación Externa
('OJ', 2023, 1, '20130541', 'BESSIE ESTELA HERRERA ESTRADA',           'ASISTENTE EJECUTIVO II',                                      'SECRETARIA DE ASUNTOS INTERNACIONALES Y COOPERACION',                             (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9466.34, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20173224', 'ANA GABRIELA REYES GONZALEZ',             'ASISTENTE EJECUTIVO II',                                      'SECRETARIA DE ASUNTOS INTERNACIONALES Y COOPERACION',                             (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),     0.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '19960049', 'SOFIA MARGARITA GRAJEDA CASTELLANOS',     'SECRETARIA EJECUTIVA III',                                    'SECRETARIA DE ASUNTOS INTERNACIONALES Y COOPERACION',                             (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  7740.70, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20160417', 'FAUSTO VINICIO CORDOVA DIAZ',             'JEFE DE DEPARTAMENTO EJECUCION DE PROYECTOS DE COOPERACION',  'DEPARTAMENTO DE EJECUCION DE PROYECTOS DE COOPERACION EXTERNA',                   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 17729.46, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20070003', 'CARLOS ALBERTO DAVILA HERRERA',           'TECNICO EN COOPERACION I',                                    'DEPARTAMENTO DE EJECUCION DE PROYECTOS DE COOPERACION EXTERNA',                   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 14055.90, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20120233', 'MONICA BEATRIZ LOPEZ CASTILLO',           'TECNICO EN COOPERACION',                                      'DEPARTAMENTO DE EJECUCION DE PROYECTOS DE COOPERACION EXTERNA',                   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 12111.75, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20130702', 'CARMEN ODILIA ESCOBAR DE LEON',           'AUXILIAR EN COOPERACION II',                                  'DEPARTAMENTO DE EJECUCION DE PROYECTOS DE COOPERACION EXTERNA',                   (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9466.34, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),

-- 28–35 Secretaría Privada y Secretaría de Política Criminal
('OJ', 2023, 1, '20180544', 'CLAUDIA LISETTE ARRECIS MENA',            'SECRETARIO PRIVADO Y DE ASUNTOS ESTRATEGICOS',                'SECRETARIA PRIVADA Y DE ASUNTOS ESTRATEGICOS',                                    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 29286.50, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20190833', 'OTTO RONALDO GONZALEZ PENA',              'SUBSECRETARIO PRIVADO Y DE ASUNTOS ESTRATEGICOS',             'SECRETARIA PRIVADA Y DE ASUNTOS ESTRATEGICOS',                                    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 21234.83, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20140017', 'MEREDITH MURCIA MARTINEZ',                'ASESOR LEGAL DE SECRETARIA PRIVADA',                          'SECRETARIA PRIVADA Y DE ASUNTOS ESTRATEGICOS',                                    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 14210.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20200566', 'CAROLL ORBELINA DEL CID AYALA',           'ASISTENTE EJECUTIVO III',                                     'SECRETARIA PRIVADA Y DE ASUNTOS ESTRATEGICOS',                                    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 12101.75, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20070131', 'CLAUDIA MARIA LARA GONZALEZ',             'ASISTENTE DE SECRETARIA PRIVADA',                             'SECRETARIA PRIVADA Y DE ASUNTOS ESTRATEGICOS',                                    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 11700.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20050090', 'MARIA ISABEL ZAMBRONI HERNANDEZ',         'ASISTENTE DE SECRETARIA PRIVADA',                             'SECRETARIA PRIVADA Y DE ASUNTOS ESTRATEGICOS',                                    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 11700.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20173102', 'EVELYN GRISELDA MONTERROSO PEREZ',        'ASISTENTE EJECUTIVO I',                                       'SECRETARIA PRIVADA Y DE ASUNTOS ESTRATEGICOS',                                    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  7740.70, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20160185', 'ILEANA BEATRIZ MARTINEZ CHAVARRIA',       'OFICINISTA I',                                                'SECRETARIA PRIVADA Y DE ASUNTOS ESTRATEGICOS',                                    (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  4860.30, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),

-- 36–41 Secretaría de Política Criminal
('OJ', 2023, 1, '20040120', 'JULIO ESTEBAN HERRERA PALACIOS',          'SUB-SECRETARIO DE POLITICA CRIMINAL',                         'SECRETARIA DE POLITICA CRIMINAL',                                                 (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 21234.83, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20150033', 'ESTUARDO JOSE RECINOS CARDONA',           'ASISTENTE EJECUTIVO IV',                                      'SECRETARIA DE POLITICA CRIMINAL',                                                 (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 13515.03, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20180530', 'OLGA MELIZA MEJIA GONZALEZ',              'ASISTENTE EJECUTIVO I',                                       'SECRETARIA DE POLITICA CRIMINAL',                                                 (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  7740.70, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20190512', 'RODOLFO SIAN HERNANDEZ',                  'CONDUCTOR DE VEHICULOS',                                      'SECRETARIA DE POLITICA CRIMINAL',                                                 (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  5659.78, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20220192', 'SERGIO ESTUARDO DE LEON MARTINEZ',        'CONDUCTOR DE VEHICULOS',                                      'SECRETARIA DE POLITICA CRIMINAL',                                                 (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  5659.78, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20173040', 'JUAN MANUEL ARIAS DE LEON',               'MENSAJERO',                                                   'SECRETARIA DE POLITICA CRIMINAL',                                                 (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  4697.04, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),

-- 42–48 Depto. Coordinación de Atención a la Víctima
('OJ', 2023, 1, '20190481', 'MAYRA PATRICIA RODAS SANTIAGO',           'JEFE DE DEPARTAMENTO DE COORDINACION DE ATENCION A LA VICTIMA', 'DEPARTAMENTO DE COORDINACION DE ATENCION A LA VICTIMA',                         (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 17736.50, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '19980063', 'MIRNA CONSUELO JUAREZ ANDRADE',           'COORDINADOR(A) AREA DE SERVICIOS INTEGRALES',                 'DEPARTAMENTO DE COORDINACION DE ATENCION A LA VICTIMA',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 15710.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20120299', 'SULMA JANNETH VARGAS CABRERA',            'TRABAJADOR SOCIAL',                                           'DEPARTAMENTO DE COORDINACION DE ATENCION A LA VICTIMA',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 14055.90, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20130409', 'JULISSA LOURDES BALDETTI PEREZ',          'TECNICO AREA LEGAL VICTIMOLOGICA',                            'DEPARTAMENTO DE COORDINACION DE ATENCION A LA VICTIMA',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9781.73, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20130677', 'DIONICIA CUIN SUY',                       'PROFESIONAL ASISTENTE DE PSICOLOGO',                          'DEPARTAMENTO DE COORDINACION DE ATENCION A LA VICTIMA',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9791.73, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '19980114', 'LOURDES AZUCENA DAVILA ESCOBEDO',         'ASISTENTE EJECUTIVO II',                                      'DEPARTAMENTO DE COORDINACION DE ATENCION A LA VICTIMA',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  9466.34, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20140635', 'DAVID JEREMIAS REYES BETETA',             'CONDUCTOR DE VEHICULOS',                                      'DEPARTAMENTO DE COORDINACION DE ATENCION A LA VICTIMA',                           (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'),  5659.78, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),

-- 49–50 Unidad de Evaluación del Desempeño
('OJ', 2023, 1, '20090289', 'JUAN FERNANDO LANUZA MUNOZ',              'JEFE DE LA UNIDAD DE EVALUACION DEL DESEMPENO',               'UNIDAD DE EVALUACION DEL DESEMPENO DEL MINISTERIO PUBLICO',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 19710.00, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv'),
('OJ', 2023, 1, '20180423', 'LUISA CECILIA NAVAS GONZALEZ',            'ANALISTA LEGAL',                                              'UNIDAD DE EVALUACION DEL DESEMPENO DEL MINISTERIO PUBLICO',                       (SELECT id FROM justicia.renglon_presupuestario WHERE codigo = '011'), 14055.90, 'OJ — Reporte LAIP Enero 2023', '01_Enero.csv');
