-- ============================================================
-- Proyecto: SS2-CONOSE-OCCIDENTE
-- Modulo: Logística, Transporte y Conectividad Vial
-- Migracion: V20260706190000__ddl_transporte.sql
-- Motor: PostgreSQL
-- Convenciones aplicadas:
--   - No se usa search_path.
--   - Todos los objetos se califican con el esquema transporte.
--   - Tablas de dominio incluyen carga_id INT REFERENCES meta.carga(id).
--   - Tablas y columnas se documentan con COMMENT ON.
-- ============================================================

DROP SCHEMA IF EXISTS transporte CASCADE;
CREATE SCHEMA IF NOT EXISTS transporte;

COMMENT ON SCHEMA transporte IS 'Esquema para el módulo de Logística, Transporte y Conectividad Vial, enfocado en facilitar información de transporte para turistas e investigadores en el Altiplano Occidental.';

-- 1. tipo_transporte
CREATE TABLE IF NOT EXISTS transporte.tipo_transporte (
    id_tipo_transporte INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo             VARCHAR(80)  NOT NULL UNIQUE,
    nombre             VARCHAR(120) NOT NULL UNIQUE,
    descripcion        TEXT,
    carga_id           INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE transporte.tipo_transporte IS 'Medios de transporte público y privado disponibles para moverse en la región.';
COMMENT ON COLUMN transporte.tipo_transporte.id_tipo_transporte IS 'Identificador único del tipo de transporte.';
COMMENT ON COLUMN transporte.tipo_transporte.codigo IS 'Código único estable del tipo de transporte (ej. TUC_TUC, CHICKEN_BUS).';
COMMENT ON COLUMN transporte.tipo_transporte.nombre IS 'Nombre común del medio (ej. Tuc-tuc, Autobús extraurbano, Shuttle turístico).';
COMMENT ON COLUMN transporte.tipo_transporte.descripcion IS 'Descripción del servicio, capacidad y cobertura habitual.';
COMMENT ON COLUMN transporte.tipo_transporte.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 2. proveedor_transporte
CREATE TABLE IF NOT EXISTS transporte.proveedor_transporte (
    id_proveedor    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(80)  NOT NULL UNIQUE,
    nombre          VARCHAR(220) NOT NULL UNIQUE,
    representante   VARCHAR(180),
    contacto        VARCHAR(150),
    departamento_id INT NOT NULL REFERENCES geografia.departamento(id),
    municipio_id    INT REFERENCES geografia.municipio(id),
    carga_id        INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE transporte.proveedor_transporte IS 'Líneas de autobuses, cooperativas de lanchas, y asociaciones locales de transportistas.';
COMMENT ON COLUMN transporte.proveedor_transporte.id_proveedor IS 'Identificador único del proveedor.';
COMMENT ON COLUMN transporte.proveedor_transporte.codigo IS 'Código estable de identificación del proveedor.';
COMMENT ON COLUMN transporte.proveedor_transporte.nombre IS 'Nombre comercial o razón social de la empresa/cooperativa.';
COMMENT ON COLUMN transporte.proveedor_transporte.representante IS 'Representante o encargado del servicio.';
COMMENT ON COLUMN transporte.proveedor_transporte.contacto IS 'Teléfono o contacto para reservaciones e información.';
COMMENT ON COLUMN transporte.proveedor_transporte.departamento_id IS 'Departamento donde reside la sede del proveedor.';
COMMENT ON COLUMN transporte.proveedor_transporte.municipio_id IS 'Municipio donde reside la sede del proveedor.';
COMMENT ON COLUMN transporte.proveedor_transporte.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 3. ruta_transporte
CREATE TABLE IF NOT EXISTS transporte.ruta_transporte (
    id_ruta_transporte   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo               VARCHAR(80)  NOT NULL UNIQUE,
    origen_municipio_id  INT NOT NULL REFERENCES geografia.municipio(id),
    destino_municipio_id INT NOT NULL REFERENCES geografia.municipio(id),
    tipo_transporte_id   INT NOT NULL REFERENCES transporte.tipo_transporte(id_tipo_transporte),
    carga_id             INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE transporte.ruta_transporte IS 'Rutas de viaje establecidas entre municipios de origen y destino.';
COMMENT ON COLUMN transporte.ruta_transporte.id_ruta_transporte IS 'Identificador único de la ruta.';
COMMENT ON COLUMN transporte.ruta_transporte.codigo IS 'Código de la ruta (ej. RT_GTM_MUNI1_MUNI2).';
COMMENT ON COLUMN transporte.ruta_transporte.origen_municipio_id IS 'Municipio de inicio del trayecto.';
COMMENT ON COLUMN transporte.ruta_transporte.destino_municipio_id IS 'Municipio de finalización del trayecto.';
COMMENT ON COLUMN transporte.ruta_transporte.tipo_transporte_id IS 'Medio de transporte principal usado en la ruta.';
COMMENT ON COLUMN transporte.ruta_transporte.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 4. itinerario_transporte
CREATE TABLE IF NOT EXISTS transporte.itinerario_transporte (
    id_itinerario             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruta_transporte_id        INT NOT NULL REFERENCES transporte.ruta_transporte(id_ruta_transporte) ON DELETE CASCADE,
    proveedor_id              INT NOT NULL REFERENCES transporte.proveedor_transporte(id_proveedor),
    hora_salida               TIME NOT NULL,
    frecuencia                VARCHAR(80) NOT NULL,
    tarifa_q                  NUMERIC(10, 2) NOT NULL,
    duracion_estimada_minutos INT NOT NULL,
    carga_id                  INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE transporte.itinerario_transporte IS 'Horarios de salida, frecuencias y tarifas del transporte por proveedor.';
COMMENT ON COLUMN transporte.itinerario_transporte.id_itinerario IS 'Identificador único del itinerario.';
COMMENT ON COLUMN transporte.itinerario_transporte.ruta_transporte_id IS 'Ruta asociada a este itinerario.';
COMMENT ON COLUMN transporte.itinerario_transporte.proveedor_id IS 'Proveedor a cargo de este horario/servicio.';
COMMENT ON COLUMN transporte.itinerario_transporte.hora_salida IS 'Hora programada de salida.';
COMMENT ON COLUMN transporte.itinerario_transporte.frecuencia IS 'Frecuencia de salidas (ej. Diario, Lunes a Viernes, Cada 20 min).';
COMMENT ON COLUMN transporte.itinerario_transporte.tarifa_q IS 'Tarifa oficial o estimada en Quetzales.';
COMMENT ON COLUMN transporte.itinerario_transporte.duracion_estimada_minutos IS 'Duración promedio del viaje en minutos.';
COMMENT ON COLUMN transporte.itinerario_transporte.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 5. tipo_via
CREATE TABLE IF NOT EXISTS transporte.tipo_via (
    id_tipo_via INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(80)  NOT NULL UNIQUE,
    nombre      VARCHAR(120) NOT NULL UNIQUE,
    descripcion TEXT,
    carga_id    INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE transporte.tipo_via IS 'Clasificación física y legal de las carreteras y vías en la región.';
COMMENT ON COLUMN transporte.tipo_via.id_tipo_via IS 'Identificador único del tipo de vía.';
COMMENT ON COLUMN transporte.tipo_via.codigo IS 'Código del tipo de vía (ej. AUTOPISTA, CARRETERA_ASFALTO, PEATONAL).';
COMMENT ON COLUMN transporte.tipo_via.nombre IS 'Nombre del tipo de vía (ej. Autopista de 4 carriles, Camino de terracería, Vía fluvial).';
COMMENT ON COLUMN transporte.tipo_via.descripcion IS 'Detalles constructivos y tipo de vehículos permitidos.';
COMMENT ON COLUMN transporte.tipo_via.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 6. tramo_vial
CREATE TABLE IF NOT EXISTS transporte.tramo_vial (
    id_tramo                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                  VARCHAR(80)  NOT NULL UNIQUE,
    nombre                  VARCHAR(220) NOT NULL,
    origen_municipio_id     INT NOT NULL REFERENCES geografia.municipio(id),
    destino_municipio_id    INT NOT NULL REFERENCES geografia.municipio(id),
    tipo_via_id             INT NOT NULL REFERENCES transporte.tipo_via(id_tipo_via),
    distancia_km            NUMERIC(8, 2) NOT NULL,
    tiempo_promedio_minutos INT NOT NULL,
    estado_transitabilidad  VARCHAR(80) NOT NULL DEFAULT 'BUENO',
    carga_id                INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE transporte.tramo_vial IS 'Segmentos reales de carreteras que conectan municipios y nodos turísticos principales.';
COMMENT ON COLUMN transporte.tramo_vial.id_tramo IS 'Identificador único del tramo vial.';
COMMENT ON COLUMN transporte.tramo_vial.codigo IS 'Código del tramo.';
COMMENT ON COLUMN transporte.tramo_vial.nombre IS 'Nombre descriptivo del tramo (ej. Interamericana Quetzaltenango - Totonicapán).';
COMMENT ON COLUMN transporte.tramo_vial.origen_municipio_id IS 'Municipio origen del tramo.';
COMMENT ON COLUMN transporte.tramo_vial.destino_municipio_id IS 'Municipio destino del tramo.';
COMMENT ON COLUMN transporte.tramo_vial.tipo_via_id IS 'Estructura constructiva del tramo.';
COMMENT ON COLUMN transporte.tramo_vial.distancia_km IS 'Distancia real en kilómetros.';
COMMENT ON COLUMN transporte.tramo_vial.tiempo_promedio_minutos IS 'Tiempo promedio de recorrido en vehículo normal.';
COMMENT ON COLUMN transporte.tramo_vial.estado_transitabilidad IS 'Estado de la vía (BUENO, REGULAR, MALO, BLOQUEADO).';
COMMENT ON COLUMN transporte.tramo_vial.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 7. incidencia_vial
CREATE TABLE IF NOT EXISTS transporte.incidencia_vial (
    id_incidencia    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo           VARCHAR(80)  NOT NULL UNIQUE,
    tramo_id         INT NOT NULL REFERENCES transporte.tramo_vial(id_tramo) ON DELETE CASCADE,
    tipo_incidencia  VARCHAR(120) NOT NULL,
    descripcion      TEXT NOT NULL,
    fecha_reporte    TIMESTAMP NOT NULL DEFAULT NOW(),
    activo           BOOLEAN NOT NULL DEFAULT TRUE,
    carga_id         INT REFERENCES meta.carga(id)
);

COMMENT ON TABLE transporte.incidencia_vial IS 'Alertas de transitabilidad, bloqueos, derrumbes u obras en los tramos viales.';
COMMENT ON COLUMN transporte.incidencia_vial.id_incidencia IS 'Identificador único de la incidencia.';
COMMENT ON COLUMN transporte.incidencia_vial.codigo IS 'Código único de la incidencia.';
COMMENT ON COLUMN transporte.incidencia_vial.tramo_id IS 'Tramo afectado por la incidencia.';
COMMENT ON COLUMN transporte.incidencia_vial.tipo_incidencia IS 'Tipo (Derrumbe, Bloqueo de carreteras, Trabajos en vía, Accidente).';
COMMENT ON COLUMN transporte.incidencia_vial.descripcion IS 'Explicación de la afectación vial.';
COMMENT ON COLUMN transporte.incidencia_vial.fecha_reporte IS 'Fecha y hora del reporte.';
COMMENT ON COLUMN transporte.incidencia_vial.activo IS 'Indica si la incidencia sigue activa afectando el paso.';
COMMENT ON COLUMN transporte.incidencia_vial.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 8. destino_transporte
CREATE TABLE IF NOT EXISTS transporte.destino_transporte (
    id_destino_transporte  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destino_id             INT NOT NULL REFERENCES turismo.destino_turistico(id_destino) ON DELETE CASCADE,
    parada_cercana         VARCHAR(220) NOT NULL,
    tipo_transporte_id     INT NOT NULL REFERENCES transporte.tipo_transporte(id_tipo_transporte),
    distancia_parada_km    NUMERIC(6, 2) NOT NULL,
    costo_traslado_local_q NUMERIC(8, 2) NOT NULL,
    tiempo_traslado_minutos INT NOT NULL,
    carga_id               INT REFERENCES meta.carga(id),
    CONSTRAINT uq_destino_transporte_parada UNIQUE (destino_id, parada_cercana, tipo_transporte_id)
);

COMMENT ON TABLE transporte.destino_transporte IS 'Integración de destinos turísticos con conectores de transporte e indicaciones de llegada.';
COMMENT ON COLUMN transporte.destino_transporte.id_destino_transporte IS 'Identificador único de la parada asociada al destino.';
COMMENT ON COLUMN transporte.destino_transporte.destino_id IS 'Identificador de la atracción turística de la tabla turismo.destino_turistico.';
COMMENT ON COLUMN transporte.destino_transporte.parada_cercana IS 'Nombre o ubicación de la parada/estación de autobús o lancha más cercana.';
COMMENT ON COLUMN transporte.destino_transporte.tipo_transporte_id IS 'Tipo de transporte que llega a dicha parada.';
COMMENT ON COLUMN transporte.destino_transporte.distancia_parada_km IS 'Distancia restante desde la parada hasta la entrada de la atracción (en km).';
COMMENT ON COLUMN transporte.destino_transporte.costo_traslado_local_q IS 'Costo promedio del traslado final (ej. tarifa de tuc-tuc en Quetzales).';
COMMENT ON COLUMN transporte.destino_transporte.tiempo_traslado_minutos IS 'Tiempo del trayecto final de conexión en minutos.';
COMMENT ON COLUMN transporte.destino_transporte.carga_id IS 'Referencia al registro de carga de metadatos.';

-- 9. conexion_municipal
CREATE TABLE IF NOT EXISTS transporte.conexion_municipal (
    id_conexion             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id            INT NOT NULL REFERENCES geografia.municipio(id),
    tipo_vehiculo           VARCHAR(80) NOT NULL DEFAULT 'LIVIANO',
    distancia_cabecera_km   NUMERIC(8, 2) NOT NULL,
    tiempo_cabecera_minutos INT NOT NULL,
    distancia_capital_km    NUMERIC(8, 2) NOT NULL,
    tiempo_capital_minutos  INT NOT NULL,
    carga_id                INT REFERENCES meta.carga(id),
    CONSTRAINT uq_conexion_muni_vehiculo UNIQUE (municipio_id, tipo_vehiculo)
);

COMMENT ON TABLE transporte.conexion_municipal IS 'Matriz de accesibilidad de municipios hacia cabeceras y capital por tipo de vehículo.';
COMMENT ON COLUMN transporte.conexion_municipal.id_conexion IS 'Identificador de la conexión.';
COMMENT ON COLUMN transporte.conexion_municipal.municipio_id IS 'Municipio analizado.';
COMMENT ON COLUMN transporte.conexion_municipal.tipo_vehiculo IS 'Tipo de vehículo utilizado para la estimación (LIVIANO, PESADO, AUTOBUS).';
COMMENT ON COLUMN transporte.conexion_municipal.distancia_cabecera_km IS 'Distancia vial a la cabecera de su departamento (en km).';
COMMENT ON COLUMN transporte.conexion_municipal.tiempo_cabecera_minutos IS 'Tiempo promedio de viaje a la cabecera (en minutos).';
COMMENT ON COLUMN transporte.conexion_municipal.distancia_capital_km IS 'Distancia vial a la Ciudad de Guatemala (en km).';
COMMENT ON COLUMN transporte.conexion_municipal.tiempo_capital_minutos IS 'Tiempo promedio de viaje a la Ciudad de Guatemala (en minutos).';
COMMENT ON COLUMN transporte.conexion_municipal.carga_id IS 'Referencia al registro de carga de metadatos.';

-- Índices adicionales para optimización de conectividad
CREATE INDEX IF NOT EXISTS ix_ruta_origen_destino ON transporte.ruta_transporte(origen_municipio_id, destino_municipio_id);
CREATE INDEX IF NOT EXISTS ix_tramo_origen_destino ON transporte.tramo_vial(origen_municipio_id, destino_municipio_id);
CREATE INDEX IF NOT EXISTS ix_itinerario_ruta ON transporte.itinerario_transporte(ruta_transporte_id);
CREATE INDEX IF NOT EXISTS ix_incidencia_tramo ON transporte.incidencia_vial(tramo_id) WHERE activo = TRUE;
